<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="fs-2 mb-0 text-gray-800">Produtos</h1>
</div>

<!-- Conteudo da Pagina -->

<?php

foreach ($this->view->dados as $indice => $produto) { ?>
    <p><?= $produto['id'] . ' - ' . $produto['descricao'] . ' - '; ?></p>
    <p><?= $produto['preco'] . ' - ' . $produto['ativo'] . ' - '; ?></p>
    <p><?= $produto['criado_em'] . '<br>'; ?></p>

    <hr>
<?php
}
?>